# Generated by Django 6.0.3 on 2026-03-04 03:32

from django.db import migrations


def create_task_status(apps, schema_editor):
    TaskStatus = apps.get_model("task", "TaskStatus")

    statuses = [
        "PENDING",
        "IN_PROGRESS",
        "COMPLETED",
    ]

    for status in statuses:
        TaskStatus.objects.get_or_create(code=status)


def delete_task_status(apps, schema_editor):
    TaskStatus = apps.get_model("task", "TaskStatus")
    TaskStatus.objects.filter(code__in=["PENDING", "IN_PROGRESS", "COMPLETED"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_task_status, delete_task_status),
    ]
